_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.7.10
        t:
            "1":
                - 1
                - 5
                - 53
                - 55
            "2":
                - 1
                - 5
                - 53
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.7.10
            "5": 0.18.7
            "8":
                - 2
                - 5
            "12": 0.18.7
            "13": linux-x86_64
MLP_params:
    value: 7745
batch_size:
    value: 128
csv_file:
    value: /home/choi/PICL/data_processed/preprocessed_battery_health_dataset_all_points.csv
device:
    value: cpu
early_stop:
    value: 20
epochs:
    value: 50
final_lr:
    value: 0.0002
log_dir:
    value: logging.txt
lr:
    value: 0.01
model:
    value: MLP
normalization_method:
    value: z-score
save_folder:
    value: /home/choi/PICL/result_small_sample_05_06_07_18
wandb_entity:
    value: null
wandb_project:
    value: battery-health-comparison
wandb_run_name:
    value: null
warmup_epochs:
    value: 30
warmup_lr:
    value: 0.002
