_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.7.10
        t:
            "1":
                - 1
                - 5
                - 53
                - 55
            "2":
                - 1
                - 5
                - 53
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.7.10
            "5": 0.18.7
            "8":
                - 2
                - 5
            "12": 0.18.7
            "13": linux-x86_64
F_hidden_dim:
    value: 128
F_layers_num:
    value: 4
alpha:
    value: 1
batch_size:
    value: 128
beta:
    value: 0.5
contrastive_weight:
    value: 0.1
csv_file:
    value: /home/choi/PICL/data_processed/preprocessed_battery_health_dataset_all_points.csv
csv_file_augmented:
    value: /home/choi/PICL/data_augmentation/battery_phys_augmented.csv
device:
    value: cpu
early_stop:
    value: 30
epochs:
    value: 100
final_lr:
    value: 1e-05
log_dir:
    value: training_log.txt
lr:
    value: 0.0005
lr_F:
    value: 0.0005
momentum:
    value: 0.999
normalization_method:
    value: z-score
pinn_params:
    value: 41986
pinn_weight:
    value: 1
projection_dim:
    value: 128
queue_size:
    value: 4096
save_folder:
    value: result_small_sample_05_06_07_18
seed:
    value: 42
temperature:
    value: 0.1
wandb_entity:
    value: null
wandb_project:
    value: battery-picle
wandb_run_name:
    value: null
warmup_epochs:
    value: 50
warmup_lr:
    value: 0.0001
wrapper_params:
    value: 84098
